export const rows = [
  {
    id: 1,
    img: "https://picsum.photos/200/300",
    product: "Samsung",
    customer: "Nikola",
    date: "2020-01-01",
    amount: 25,
    method: "Cash",
    status: "Pending",
  },
  {
    id: 2,
    img: "https://picsum.photos/200/300",
    product: "iPhone",
    customer: "Dusan",
    date: "2020-01-01",
    amount: 3,
    method: "Debit Card",
    status: "Aproved",
  },
  {
    id: 3,
    img: "https://picsum.photos/200/300",
    product: "iPad",
    customer: "Mladenovic13",
    date: "2020-01-01",
    amount: 12,
    method: "Cash",
    status: "Aproved",
  },
  {
    id: 4,
    img: "https://picsum.photos/200/300",
    product: "MacBook",
    customer: "Mladenovic13",
    date: "2020-01-01",
    amount: 3,
    method: "Cash",
    status: "Pending",
  },
  {
    id: 5,
    img: "https://picsum.photos/200/300",
    product: "Laptop",
    customer: "Mladenovic13",
    date: "2020-01-01",
    amount: 8,
    method: "Cash",
    status: "Aproved",
  },
];
export default rows;
