export const rows = [
  {
    id: 1,
    product: "Product 1",
    amount: 1,
    img: "https://picsum.photos/200/300",
    date: "2020-01-01",
    customer: "Mladenovic13",
    method: "Cash",
    status: "Pending",
  },
  {
    id: 2,
    product: "Product 2",
    amount: 2,
    img: "https://picsum.photos/200/300",
    customer: "Mladenovic13",
    date: "2020-01-01",
    method: "Cash",
    status: "Approved",
  },
  {
    id: 3,
    product: "Product 3",
    customer: "Mladenovic13",
    amount: 3,
    img: "https://picsum.photos/200/300",
    date: "2020-01-01",
    method: "Cash",
    status: "Pending",
  },
  {
    id: 4,
    product: "Product 4",
    customer: "Mladenovic13",
    amount: 1,
    img: "https://picsum.photos/200/300",
    date: "2020-01-01",
    method: "Cash",
    status: "Pending",
  },
  {
    id: 5,
    product: "Product 5",
    customer: "Mladenovic13",
    amount: 2,
    img: "https://picsum.photos/200/300",
    date: "2020-01-01",
    method: "Cash",
    status: "Approved",
  },
  {
    id: 6,
    product: "Product 6",
    customer: "Mladenovic13",
    amount: 3,
    img: "https://picsum.photos/200/300",
    date: "2020-01-01",
    method: "Cash",
    status: "Approved",
  },
];
export default rows;
